#!/usr/bin/env bash
# Description: Pings an IP address passed as an argument
if [ "$#" != 1 ]; then
	echo "Error: Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi
if ! [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	echo "Error: '$1' is not a valid IP address"
	exit 1
fi
ping -c 5 "$1"
