#!/usr/bin/env bash
# Description: Configures an Ubuntu server to map localhost
sudo cp /etc/hosts /etc/hosts.bak
if [ $? -ne 0 ]; then
	echo "Error: Failed to create a backup of the hosts file"
	exit 1
fi
echo "127.0.0.2       localhost" | sudo tee ~/hosts.new > /dev/null
echo "8.8.8.8         facebook.com" | sudo tee -a ~/hosts.new > /dev/null
sudo cp -f ~/hosts.new /etc/hosts
if [ $? -ne 0 ]; then
	echo "Error: Failed to update the hosts file"
	exit 1
fi
echo "Hosts file configured successfully"

